spring:
  application:
    name: chronos
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:chronos}
    username: ${DB_USER:chronos_user}
    password: ${DB_PASSWORD:chronos_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

# Настройки логирования для Docker
logging:
  level:
    com.chronos: INFO
    org.springframework.web: INFO
    liquibase: INFO
    reactor.netty: WARN
    io.netty: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints для health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# JWT конфигурация
jwt:
  secret: ${JWT_SECRET:chronos-super-secret-key-change-in-production-please-make-it-longer-than-256-bits}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 часа в миллисекундах
